defconfig: Enable CONFIG_POWER_RESET_HISI
Comparing the KMI and the symbol lists:
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - __device_reset
 - __devm_reset_control_get
 - __of_reset_control_get
 - __reset_control_get
 - devm_reset_control_array_get
 - devm_reset_controller_register
 - of_reset_control_array_get
 - reset_control_assert
 - reset_control_deassert
 - reset_control_put
 - reset_control_reset
 - reset_controller_register
 - reset_controller_unregister

Signed-off-by: dopaemon <polarisdp@gmail.com>